service: serverless-url-shortener

provider:
  name: aws
  runtime: nodejs4.3

  stage: dev
  region: eu-west-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:dynamodb:"
            - "Ref" : "AWS::Region"
            - ":"
            - "Ref" : "AWS::AccountId"
            - ":table/"
            - "Ref" : "urlsTable"
package:
  exclude:
    - .idea
    - coverage/**
    - spec
    - node_modules/**

functions:
  resourceGet:
    handler: code/lambda/shortener-crud/list/handler.handler
    events:
      - http:
          path: r
          method: get

# you can add CloudFormation resource templates here
resources:
  Resources:
    urlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sls-url-shortener-urls-${opt:stage}
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

#  Outputs:
#    UrlTable:
#      Description: "Table containing every Url shortened"
#      Value:
#        - "Ref" : "urlsTable"
